// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base64_decode`, `base64_encode`, `base64_url_decode_with_prefix`, `base64_url_encode_with_prefix`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Generate a single minimum range proof: value >= min
///
/// # Arguments
/// * `value` - The value to prove
/// * `min` - The minimum bound
/// * `bit_size` - Number of bits (typically 32 or 64)
/// * `domain` - Domain separator for the proof (e.g., "zetrix-vc")
Future<BulletproofResult> generateSingleMinRangeProof(
        {required PlatformInt64 value,
        required PlatformInt64 min,
        required int bitSize,
        required String domain}) =>
    RustLib.instance.api.crateApiGenerateSingleMinRangeProof(
        value: value, min: min, bitSize: bitSize, domain: domain);

/// Generate a single maximum range proof: value <= max
Future<BulletproofResult> generateSingleMaxRangeProof(
        {required PlatformInt64 value,
        required PlatformInt64 max,
        required int bitSize,
        required String domain}) =>
    RustLib.instance.api.crateApiGenerateSingleMaxRangeProof(
        value: value, max: max, bitSize: bitSize, domain: domain);

/// Generate a single min-max range proof: min <= value <= max
Future<BulletproofResult> generateSingleMinMaxRangeProof(
        {required PlatformInt64 value,
        required PlatformInt64 min,
        required PlatformInt64 max,
        required int bitSize,
        required String domain}) =>
    RustLib.instance.api.crateApiGenerateSingleMinMaxRangeProof(
        value: value, min: min, max: max, bitSize: bitSize, domain: domain);

/// Generate multiple minimum range proofs: values[i] >= mins[i]
Future<BulletproofResult> generateMultipleMinRangeProof(
        {required Int64List values,
        required Int64List mins,
        required int bitSize,
        required String domain}) =>
    RustLib.instance.api.crateApiGenerateMultipleMinRangeProof(
        values: values, mins: mins, bitSize: bitSize, domain: domain);

/// Generate multiple maximum range proofs: values[i] <= maxs[i]
Future<BulletproofResult> generateMultipleMaxRangeProof(
        {required Int64List values,
        required Int64List maxs,
        required int bitSize,
        required String domain}) =>
    RustLib.instance.api.crateApiGenerateMultipleMaxRangeProof(
        values: values, maxs: maxs, bitSize: bitSize, domain: domain);

/// Generate multiple min-max range proofs: mins[i] <= values[i] <= maxs[i]
/// Use max=0 to indicate no maximum constraint (only minimum)
Future<BulletproofResult> generateMultipleMinMaxRangeProof(
        {required Int64List values,
        required Int64List mins,
        required Int64List maxs,
        required int bitSize,
        required String domain}) =>
    RustLib.instance.api.crateApiGenerateMultipleMinMaxRangeProof(
        values: values,
        mins: mins,
        maxs: maxs,
        bitSize: bitSize,
        domain: domain);

/// Verify a bulletproof range proof
Future<VerificationResult> verifyMultipleRangeProof(
        {required int bitSize,
        required String proofValue,
        required List<String> commitments,
        required String domain}) =>
    RustLib.instance.api.crateApiVerifyMultipleRangeProof(
        bitSize: bitSize,
        proofValue: proofValue,
        commitments: commitments,
        domain: domain);

/// Verify a single min-max range proof
Future<VerificationResult> verifySingleMinMaxRangeProof(
        {required PlatformInt64 min,
        required PlatformInt64 max,
        required int bitSize,
        required String proofValue,
        required List<String> commitments,
        required String domain}) =>
    RustLib.instance.api.crateApiVerifySingleMinMaxRangeProof(
        min: min,
        max: max,
        bitSize: bitSize,
        proofValue: proofValue,
        commitments: commitments,
        domain: domain);

/// Verify multiple min-max range proofs
Future<VerificationResult> verifyMultipleMinMaxRangeProof(
        {required Int64List mins,
        required Int64List maxs,
        required int bitSize,
        required String proofValue,
        required List<String> commitments,
        required String domain}) =>
    RustLib.instance.api.crateApiVerifyMultipleMinMaxRangeProof(
        mins: mins,
        maxs: maxs,
        bitSize: bitSize,
        proofValue: proofValue,
        commitments: commitments,
        domain: domain);

/// Result type for bulletproof operations
class BulletproofResult {
  final bool success;
  final String proofValue;
  final List<String> commitments;
  final String errorMessage;

  const BulletproofResult({
    required this.success,
    required this.proofValue,
    required this.commitments,
    required this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      proofValue.hashCode ^
      commitments.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BulletproofResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          proofValue == other.proofValue &&
          commitments == other.commitments &&
          errorMessage == other.errorMessage;
}

/// Verification result
class VerificationResult {
  final bool success;
  final bool isValid;
  final String errorMessage;

  const VerificationResult({
    required this.success,
    required this.isValid,
    required this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^ isValid.hashCode ^ errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerificationResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          isValid == other.isValid &&
          errorMessage == other.errorMessage;
}
