// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1246900537;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'bulletproof',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<BulletproofResult> crateApiGenerateMultipleMaxRangeProof(
      {required Int64List values,
      required Int64List maxs,
      required int bitSize,
      required String domain});

  Future<BulletproofResult> crateApiGenerateMultipleMinMaxRangeProof(
      {required Int64List values,
      required Int64List mins,
      required Int64List maxs,
      required int bitSize,
      required String domain});

  Future<BulletproofResult> crateApiGenerateMultipleMinRangeProof(
      {required Int64List values,
      required Int64List mins,
      required int bitSize,
      required String domain});

  Future<BulletproofResult> crateApiGenerateSingleMaxRangeProof(
      {required PlatformInt64 value,
      required PlatformInt64 max,
      required int bitSize,
      required String domain});

  Future<BulletproofResult> crateApiGenerateSingleMinMaxRangeProof(
      {required PlatformInt64 value,
      required PlatformInt64 min,
      required PlatformInt64 max,
      required int bitSize,
      required String domain});

  Future<BulletproofResult> crateApiGenerateSingleMinRangeProof(
      {required PlatformInt64 value,
      required PlatformInt64 min,
      required int bitSize,
      required String domain});

  Future<VerificationResult> crateApiVerifyMultipleMinMaxRangeProof(
      {required Int64List mins,
      required Int64List maxs,
      required int bitSize,
      required String proofValue,
      required List<String> commitments,
      required String domain});

  Future<VerificationResult> crateApiVerifyMultipleRangeProof(
      {required int bitSize,
      required String proofValue,
      required List<String> commitments,
      required String domain});

  Future<VerificationResult> crateApiVerifySingleMinMaxRangeProof(
      {required PlatformInt64 min,
      required PlatformInt64 max,
      required int bitSize,
      required String proofValue,
      required List<String> commitments,
      required String domain});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BulletproofResult> crateApiGenerateMultipleMaxRangeProof(
      {required Int64List values,
      required Int64List maxs,
      required int bitSize,
      required String domain}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_i_64_strict(values, serializer);
        sse_encode_list_prim_i_64_strict(maxs, serializer);
        sse_encode_i_32(bitSize, serializer);
        sse_encode_String(domain, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bulletproof_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGenerateMultipleMaxRangeProofConstMeta,
      argValues: [values, maxs, bitSize, domain],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateMultipleMaxRangeProofConstMeta =>
      const TaskConstMeta(
        debugName: "generate_multiple_max_range_proof",
        argNames: ["values", "maxs", "bitSize", "domain"],
      );

  @override
  Future<BulletproofResult> crateApiGenerateMultipleMinMaxRangeProof(
      {required Int64List values,
      required Int64List mins,
      required Int64List maxs,
      required int bitSize,
      required String domain}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_i_64_strict(values, serializer);
        sse_encode_list_prim_i_64_strict(mins, serializer);
        sse_encode_list_prim_i_64_strict(maxs, serializer);
        sse_encode_i_32(bitSize, serializer);
        sse_encode_String(domain, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bulletproof_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGenerateMultipleMinMaxRangeProofConstMeta,
      argValues: [values, mins, maxs, bitSize, domain],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateMultipleMinMaxRangeProofConstMeta =>
      const TaskConstMeta(
        debugName: "generate_multiple_min_max_range_proof",
        argNames: ["values", "mins", "maxs", "bitSize", "domain"],
      );

  @override
  Future<BulletproofResult> crateApiGenerateMultipleMinRangeProof(
      {required Int64List values,
      required Int64List mins,
      required int bitSize,
      required String domain}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_i_64_strict(values, serializer);
        sse_encode_list_prim_i_64_strict(mins, serializer);
        sse_encode_i_32(bitSize, serializer);
        sse_encode_String(domain, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bulletproof_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGenerateMultipleMinRangeProofConstMeta,
      argValues: [values, mins, bitSize, domain],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateMultipleMinRangeProofConstMeta =>
      const TaskConstMeta(
        debugName: "generate_multiple_min_range_proof",
        argNames: ["values", "mins", "bitSize", "domain"],
      );

  @override
  Future<BulletproofResult> crateApiGenerateSingleMaxRangeProof(
      {required PlatformInt64 value,
      required PlatformInt64 max,
      required int bitSize,
      required String domain}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(value, serializer);
        sse_encode_i_64(max, serializer);
        sse_encode_i_32(bitSize, serializer);
        sse_encode_String(domain, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bulletproof_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGenerateSingleMaxRangeProofConstMeta,
      argValues: [value, max, bitSize, domain],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateSingleMaxRangeProofConstMeta =>
      const TaskConstMeta(
        debugName: "generate_single_max_range_proof",
        argNames: ["value", "max", "bitSize", "domain"],
      );

  @override
  Future<BulletproofResult> crateApiGenerateSingleMinMaxRangeProof(
      {required PlatformInt64 value,
      required PlatformInt64 min,
      required PlatformInt64 max,
      required int bitSize,
      required String domain}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(value, serializer);
        sse_encode_i_64(min, serializer);
        sse_encode_i_64(max, serializer);
        sse_encode_i_32(bitSize, serializer);
        sse_encode_String(domain, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bulletproof_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGenerateSingleMinMaxRangeProofConstMeta,
      argValues: [value, min, max, bitSize, domain],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateSingleMinMaxRangeProofConstMeta =>
      const TaskConstMeta(
        debugName: "generate_single_min_max_range_proof",
        argNames: ["value", "min", "max", "bitSize", "domain"],
      );

  @override
  Future<BulletproofResult> crateApiGenerateSingleMinRangeProof(
      {required PlatformInt64 value,
      required PlatformInt64 min,
      required int bitSize,
      required String domain}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(value, serializer);
        sse_encode_i_64(min, serializer);
        sse_encode_i_32(bitSize, serializer);
        sse_encode_String(domain, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bulletproof_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGenerateSingleMinRangeProofConstMeta,
      argValues: [value, min, bitSize, domain],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateSingleMinRangeProofConstMeta =>
      const TaskConstMeta(
        debugName: "generate_single_min_range_proof",
        argNames: ["value", "min", "bitSize", "domain"],
      );

  @override
  Future<VerificationResult> crateApiVerifyMultipleMinMaxRangeProof(
      {required Int64List mins,
      required Int64List maxs,
      required int bitSize,
      required String proofValue,
      required List<String> commitments,
      required String domain}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_i_64_strict(mins, serializer);
        sse_encode_list_prim_i_64_strict(maxs, serializer);
        sse_encode_i_32(bitSize, serializer);
        sse_encode_String(proofValue, serializer);
        sse_encode_list_String(commitments, serializer);
        sse_encode_String(domain, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_verification_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiVerifyMultipleMinMaxRangeProofConstMeta,
      argValues: [mins, maxs, bitSize, proofValue, commitments, domain],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVerifyMultipleMinMaxRangeProofConstMeta =>
      const TaskConstMeta(
        debugName: "verify_multiple_min_max_range_proof",
        argNames: [
          "mins",
          "maxs",
          "bitSize",
          "proofValue",
          "commitments",
          "domain"
        ],
      );

  @override
  Future<VerificationResult> crateApiVerifyMultipleRangeProof(
      {required int bitSize,
      required String proofValue,
      required List<String> commitments,
      required String domain}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(bitSize, serializer);
        sse_encode_String(proofValue, serializer);
        sse_encode_list_String(commitments, serializer);
        sse_encode_String(domain, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_verification_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiVerifyMultipleRangeProofConstMeta,
      argValues: [bitSize, proofValue, commitments, domain],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVerifyMultipleRangeProofConstMeta =>
      const TaskConstMeta(
        debugName: "verify_multiple_range_proof",
        argNames: ["bitSize", "proofValue", "commitments", "domain"],
      );

  @override
  Future<VerificationResult> crateApiVerifySingleMinMaxRangeProof(
      {required PlatformInt64 min,
      required PlatformInt64 max,
      required int bitSize,
      required String proofValue,
      required List<String> commitments,
      required String domain}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(min, serializer);
        sse_encode_i_64(max, serializer);
        sse_encode_i_32(bitSize, serializer);
        sse_encode_String(proofValue, serializer);
        sse_encode_list_String(commitments, serializer);
        sse_encode_String(domain, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_verification_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiVerifySingleMinMaxRangeProofConstMeta,
      argValues: [min, max, bitSize, proofValue, commitments, domain],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVerifySingleMinMaxRangeProofConstMeta =>
      const TaskConstMeta(
        debugName: "verify_single_min_max_range_proof",
        argNames: [
          "min",
          "max",
          "bitSize",
          "proofValue",
          "commitments",
          "domain"
        ],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BulletproofResult dco_decode_bulletproof_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BulletproofResult(
      success: dco_decode_bool(arr[0]),
      proofValue: dco_decode_String(arr[1]),
      commitments: dco_decode_list_String(arr[2]),
      errorMessage: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VerificationResult dco_decode_verification_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VerificationResult(
      success: dco_decode_bool(arr[0]),
      isValid: dco_decode_bool(arr[1]),
      errorMessage: dco_decode_String(arr[2]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BulletproofResult sse_decode_bulletproof_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_proofValue = sse_decode_String(deserializer);
    var var_commitments = sse_decode_list_String(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    return BulletproofResult(
        success: var_success,
        proofValue: var_proofValue,
        commitments: var_commitments,
        errorMessage: var_errorMessage);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VerificationResult sse_decode_verification_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_isValid = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    return VerificationResult(
        success: var_success,
        isValid: var_isValid,
        errorMessage: var_errorMessage);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bulletproof_result(
      BulletproofResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.proofValue, serializer);
    sse_encode_list_String(self.commitments, serializer);
    sse_encode_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_verification_result(
      VerificationResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_bool(self.isValid, serializer);
    sse_encode_String(self.errorMessage, serializer);
  }
}
